const data = {
  "Star Wars": {
    name: "Star Wars",
    logo: "/images/starwars/lightsaber.webp",
    mainlogo: "/images/starwars/mainlogo.webp",
    divLogo: "/images/starwars/deathstar2.webp",
    bgHeadImage: "/images/starwars/background1.webp",
    divCol: "#383838",
    bgc: "Black",
    divEffect: "star-flourish",
    currentColor: "rgba(218,0,255,0.6)",
    highColor: "rgba(0,252,253,0.6)",
    cards: [
      { url: "/images/starwars/cards/bb8.webp", name: "BB-8", id: 1 },
      { url: "/images/starwars/cards/c3po.webp", name: "C3PO", id: 2 },
      {
        url: "/images/starwars/cards/chewbacca.webp",
        name: "Chewbacca",
        id: 3,
      },
      { url: "/images/starwars/cards/leia.webp", name: "Leia", id: 4 },
      { url: "/images/starwars/cards/obiwan.webp", name: "Obi-Wan", id: 5 },
      { url: "/images/starwars/cards/r2d2.webp", name: "R2D2", id: 6 },
      { url: "/images/starwars/cards/ren.webp", name: "Kylo-Ren", id: 7 },
      {
        url: "/images/starwars/cards/stormtrooper.webp",
        name: "Stormtrooper",
        id: 8,
      },
    ],
    bgMainImg: "/images/starwars/bg5.webp",
  },
  Pokemon: {
    name: "Pokemon",
    logo: "/images/pokemon/pokelogo3.webp",
    mainlogo: "/images/pokemon/mainlogo.webp",
    divCol: "#383838",
    bgc: "#ef0e3d",
    divEffect: "poke-flourish",
    currentColor: "#ffb5b5",
    highColor: "#b5ffb5",
    cards: [
      { url: "/images/pokemon/cards/Articuno.webp", name: "Articuno", id: 1 },
      { url: "/images/pokemon/cards/Blastoise.webp", name: "Blastoise", id: 2 },
      { url: "/images/pokemon/cards/Bulbasaur.webp", name: "Bulbasaur", id: 3 },
      { url: "/images/pokemon/cards/Celebi.webp", name: "Celebi", id: 4 },
      { url: "/images/pokemon/cards/Charizard.webp", name: "Charizard", id: 5 },
      {
        url: "/images/pokemon/cards/Charmander.webp",
        name: "Charmander",
        id: 6,
      },
      {
        url: "/images/pokemon/cards/Charmeleon.webp",
        name: "Charmeleon",
        id: 7,
      },
      { url: "/images/pokemon/cards/Chikorita.webp", name: "Chikorita", id: 8 },
      { url: "/images/pokemon/cards/Cyndaquil.webp", name: "Cyndaquil", id: 9 },
      { url: "/images/pokemon/cards/Entei.webp", name: "Entei", id: 10 },
      { url: "/images/pokemon/cards/Groudon.webp", name: "Groudon", id: 11 },
      { url: "/images/pokemon/cards/Gyarados.webp", name: "Gyarados", id: 12 },
      { url: "/images/pokemon/cards/Ivysaur.webp", name: "Ivysaur", id: 13 },
      { url: "/images/pokemon/cards/Kyogre.webp", name: "Kyogre", id: 14 },
      { url: "/images/pokemon/cards/Lapras.webp", name: "Lapras", id: 15 },
      { url: "/images/pokemon/cards/Latias.webp", name: "Latias", id: 16 },
      { url: "/images/pokemon/cards/Latios.webp", name: "Latios", id: 17 },
      { url: "/images/pokemon/cards/Lugia.webp", name: "Lugia", id: 18 },
      { url: "/images/pokemon/cards/Magmar.webp", name: "Magmar", id: 19 },
      { url: "/images/pokemon/cards/Mew.webp", name: "Mew", id: 20 },
      { url: "/images/pokemon/cards/MewTwo.webp", name: "MewTwo", id: 21 },
      { url: "/images/pokemon/cards/Moltres.webp", name: "Moltres", id: 22 },
      { url: "/images/pokemon/cards/Rayquaza.webp", name: "Rayquaza", id: 23 },
      { url: "/images/pokemon/cards/Scyther.webp", name: "Scyther", id: 24 },
      { url: "/images/pokemon/cards/Squirtle.webp", name: "Squirtle", id: 25 },
      { url: "/images/pokemon/cards/Suicune.webp", name: "Suicune", id: 26 },
      { url: "/images/pokemon/cards/Totodile.webp", name: "Totodile", id: 27 },
      {
        url: "/images/pokemon/cards/Tyranitar.webp",
        name: "Tyranitar",
        id: 28,
      },
      { url: "/images/pokemon/cards/Venusaur.webp", name: "Venusaur", id: 29 },
      {
        url: "/images/pokemon/cards/Wartortle.webp",
        name: "Wartortle",
        id: 30,
      },
      { url: "/images/pokemon/cards/Zapdos.webp", name: "Zapdos", id: 31 },
    ],
    bgMainImg: "/images/pokemon/pokemonbg2.webp",
  },
  LOTR: {
    name: "LOTR",
    logo: "/images/lotr/lotr1.webp",
    mainlogo: "/images/lotr/title.webp",
    divLogo: "/images/lotr/lotr4.webp",
    bgHeadImage: "/images/lotr/bg.webp",
    divCol: "#383838",
    bgc: "#80530e",
    divEffect: "star-flourish",
    currentColor: "#ffb5b5",
    highColor: "#b5ffb5",
    cards: [
      { url: "/images/lotr/aragorn.webp", name: "Aragorn", id: 1 },
      { url: "/images/lotr/frodo.webp", name: "Frodo", id: 2 },
      { url: "/images/lotr/gandalf2.webp", name: "Gandalf", id: 3 },
      { url: "/images/lotr/gimli1.webp", name: "Gimli", id: 4 },
      { url: "/images/lotr/legolas4.webp", name: "Legolas", id: 5 },
      { url: "/images/lotr/marry1.webp", name: "Marry", id: 6 },
      { url: "/images/lotr/pippin.webp", name: "Pippin", id: 7 },
      { url: "/images/lotr/sam1.webp", name: "Sam", id: 8 },
      { url: "/images/lotr/sauron1.png", name: "Sauron", id: 9 },
      { url: "/images/lotr/smeagol3.webp", name: "Smeagol", id: 10 },
    ],
    bgMainImg: "/images/lotr/bg2.webp",
  },
  "Rick and Morty": {
    name: "Rick and Morty",
    logo: "/images/rickandmorty/schwifty.webp",
    mainlogo: "/images/rickandmorty/header.webp",
    divLogo: "/images/rickandmorty/portal1.webp",
    bgHeadImage: "/images/rickandmorty/spacebg.webp",
    divCol: "#383838",
    bgc: "#00afc7",
    divEffect: "star-flourish",
    currentColor: "#f8ec44",
    highColor: "#62ef24",
    cards: [
      {
        url: "/images/rickandmorty/cards/picklerick.webp",
        name: "Pickle Rick",
        id: 1,
      },
      {
        url: "/images/rickandmorty/cards/rm1.webp",
        name: "Mechatronics Rick",
        id: 2,
      },
      {
        url: "/images/rickandmorty/cards/rm2.webp",
        name: "Dancing Rick and Morty",
        id: 3,
      },
      {
        url: "/images/rickandmorty/cards/rm3.webp",
        name: "Nonchalant Rick and Morty",
        id: 4,
      },
      {
        url: "/images/rickandmorty/cards/rm4.webp",
        name: "Are you seeing this Rick and Morty",
        id: 5,
      },
      { url: "/images/rickandmorty/cards/rm5.webp", name: "Chef Morty", id: 6 },
      { url: "/images/rickandmorty/cards/rm6.webp", name: "Anime Rick", id: 7 },
      {
        url: "/images/rickandmorty/cards/rm7.webp",
        name: "Scared Morty",
        id: 8,
      },
      { url: "/images/rickandmorty/cards/rm8.webp", name: "Angry Rick", id: 9 },
      {
        url: "/images/rickandmorty/cards/rm9.webp",
        name: "Wub-a-lub-a-dub-dub-Rick",
        id: 10,
      },
      {
        url: "/images/rickandmorty/cards/rm10.webp",
        name: "Satisfied Rick and Morty",
        id: 11,
      },
      {
        url: "/images/rickandmorty/cards/rm11.webp",
        name: "Tattoo Rick",
        id: 12,
      },
      {
        url: "/images/rickandmorty/cards/rm12.webp",
        name: "Confused Morty",
        id: 13,
      },
      {
        url: "/images/rickandmorty/cards/slimerick.webp",
        name: "Slime Rick",
        id: 14,
      },
      { url: "/images/rickandmorty/cards/jerry.webp", name: "Jerry", id: 15 },
    ],
    bgMainImg: "/images/rickandmorty/bg3.webp",
  },
  Cows: {
    name: "Cows",
    logo: "/images/cows/logo2.webp",
    mainlogo: "/images/cows/cowslogo.webp",
    divLogo: "/images/cows/logo3.webp",
    bgHeadImage: "/images/cows/headbg.webp",
    divCol: "#383838",
    bgc: "black",
    divEffect: "star-flourish",
    currentColor: "#4d4b4b",
    highColor: "#e5e3e3",
    cards: [
      { url: "/images/cows/cards/bessy.webp", name: "Bessy", id: 1 },
      { url: "/images/cows/cards/daisy.webp", name: "Daisy", id: 2 },
      { url: "/images/cows/cards/siobhan.webp", name: "Siobhan", id: 3 },
      { url: "/images/cows/cards/bertha.webp", name: "Bertha", id: 4 },
      { url: "/images/cows/cards/shyvonne1.webp", name: "Shyvonne", id: 5 },
      { url: "/images/cows/cards/sally.webp", name: "Sally", id: 6 },
      { url: "/images/cows/cards/griswalda.webp", name: "Griswalda", id: 7 },
      { url: "/images/cows/cards/helga.webp", name: "Helga", id: 8 },
      { url: "/images/cows/cards/sauron.webp", name: "Sauron", id: 9 },
      { url: "/images/cows/cards/mary.webp", name: "Mary", id: 10 },
      { url: "/images/cows/cards/jennifer.webp", name: "Jennifer", id: 11 },
      { url: "/images/cows/cards/petal.webp", name: "Petal", id: 12 },
      { url: "/images/cows/cards/maisy.webp", name: "Maisy", id: 13 },
      { url: "/images/cows/cards/jess.webp", name: "Jess", id: 14 },
      { url: "/images/cows/cards/tess.webp", name: "Tess", id: 15 },
      { url: "/images/cows/cards/ness.webp", name: "Ness", id: 16 },
      { url: "/images/cows/cards/susan.webp", name: "Susan", id: 17 },
      { url: "/images/cows/cards/moo.webp", name: "Moo", id: 18 },
      {
        url: "/images/cows/cards/definitelycow.webp",
        name: "Definitely Cow",
        id: 19,
      },
    ],
    bgMainImg: "/images/cows/bg5.webp",
  },
}

export default data
