const data = {
  "Star Wars": {
    name: "Star Wars",
    logo: "/images/starwars/lightsaber.png",
    mainlogo: "/images/starwars/mainlogo.png",
    divLogo: "/images/starwars/deathstar2.png",
    bgHeadImage: "/images/starwars/background1.jpg",
    divCol: "#383838",
    bgc: "Black",
    divEffect: "star-flourish",
    currentColor: "rgba(218,0,255,0.6)",
    highColor: "rgba(0,252,253,0.6)",
    cards: [
      { url: "/images/starwars/cards/bb8.png", name: "BB-8", id: 1 },
      { url: "/images/starwars/cards/c3po.png", name: "C3PO", id: 2 },
      { url: "/images/starwars/cards/chewbacca.png", name: "Chewbacca", id: 3 },
      { url: "/images/starwars/cards/leia.png", name: "Leia", id: 4 },
      { url: "/images/starwars/cards/obiwan.png", name: "Obi-Wan", id: 5 },
      { url: "/images/starwars/cards/r2d2.png", name: "R2D2", id: 6 },
      { url: "/images/starwars/cards/ren.png", name: "Kylo-Ren", id: 7 },
      {
        url: "/images/starwars/cards/stormtrooper.png",
        name: "Stormtrooper",
        id: 8,
      },
    ],
    bgMainImg: "/images/starwars/bg5.jpg",
  },
  Pokemon: {
    name: "Pokemon",
    logo: "/images/pokemon/pokelogo3.png",
    mainlogo: "/images/pokemon/mainlogo.png",
    divCol: "#383838",
    bgc: "#ef0e3d",
    divEffect: "poke-flourish",
    currentColor: "#ffb5b5",
    highColor: "#b5ffb5",
    cards: [
      { url: "/images/pokemon/cards/Articuno.png", name: "Articuno", id: 1 },
      { url: "/images/pokemon/cards/Blastoise.png", name: "Blastoise", id: 2 },
      { url: "/images/pokemon/cards/Bulbasaur.png", name: "Bulbasaur", id: 3 },
      { url: "/images/pokemon/cards/Celebi.png", name: "Celebi", id: 4 },
      { url: "/images/pokemon/cards/Charizard.png", name: "Charizard", id: 5 },
      {
        url: "/images/pokemon/cards/Charmander.png",
        name: "Charmander",
        id: 6,
      },
      {
        url: "/images/pokemon/cards/Charmeleon.png",
        name: "Charmeleon",
        id: 7,
      },
      { url: "/images/pokemon/cards/Chikorita.png", name: "Chikorita", id: 8 },
      { url: "/images/pokemon/cards/Cyndaquil.png", name: "Cyndaquil", id: 9 },
      { url: "/images/pokemon/cards/Entei.png", name: "Entei", id: 10 },
      { url: "/images/pokemon/cards/Groudon.png", name: "Groudon", id: 11 },
      { url: "/images/pokemon/cards/Gyarados.png", name: "Gyarados", id: 12 },
      { url: "/images/pokemon/cards/Ivysaur.png", name: "Ivysaur", id: 13 },
      { url: "/images/pokemon/cards/Kyogre.png", name: "Kyogre", id: 14 },
      { url: "/images/pokemon/cards/Lapras.png", name: "Lapras", id: 15 },
      { url: "/images/pokemon/cards/Latias.png", name: "Latias", id: 16 },
      { url: "/images/pokemon/cards/Latios.png", name: "Latios", id: 17 },
      { url: "/images/pokemon/cards/Lugia.png", name: "Lugia", id: 18 },
      { url: "/images/pokemon/cards/Magmar.png", name: "Magmar", id: 19 },
      { url: "/images/pokemon/cards/Mew.png", name: "Mew", id: 20 },
      { url: "/images/pokemon/cards/MewTwo.png", name: "MewTwo", id: 21 },
      { url: "/images/pokemon/cards/Moltres.png", name: "Moltres", id: 22 },
      { url: "/images/pokemon/cards/Rayquaza.png", name: "Rayquaza", id: 23 },
      { url: "/images/pokemon/cards/Scyther.png", name: "Scyther", id: 24 },
      { url: "/images/pokemon/cards/Squirtle.png", name: "Squirtle", id: 25 },
      { url: "/images/pokemon/cards/Suicune.png", name: "Suicune", id: 26 },
      { url: "/images/pokemon/cards/Totodile.png", name: "Totodile", id: 27 },
      { url: "/images/pokemon/cards/Tyranitar.png", name: "Tyranitar", id: 28 },
      { url: "/images/pokemon/cards/Venusaur.png", name: "Venusaur", id: 29 },
      { url: "/images/pokemon/cards/Wartortle.png", name: "Wartortle", id: 30 },
      { url: "/images/pokemon/cards/Zapdos.png", name: "Zapdos", id: 31 },
    ],
    bgMainImg: "/images/pokemon/pokemonbg2.png",
  },
  LOTR: {
    name: "LOTR",
    logo: "/images/lotr/lotr1.png",
    mainlogo: "/images/lotr/title.png",
    divLogo: "/images/lotr/lotr4.png",
    bgHeadImage: "/images/lotr/bg.jpg",
    divCol: "#383838",
    bgc: "#80530e",
    divEffect: "star-flourish",
    currentColor: "#ffb5b5",
    highColor: "#b5ffb5",
    cards: [
      { url: "/images/lotr/aragorn.jpeg", name: "Aragorn", id: 1 },
      { url: "/images/lotr/frodo.jpg", name: "Frodo", id: 2 },
      { url: "/images/lotr/gandalf2.png", name: "Gandalf", id: 3 },
      { url: "/images/lotr/gimli1.png", name: "Gimli", id: 4 },
      { url: "/images/lotr/legolas4.png", name: "Legolas", id: 5 },
      { url: "/images/lotr/marry1.png", name: "Marry", id: 6 },
      { url: "/images/lotr/pippin.jpeg", name: "Pippin", id: 7 },
      { url: "/images/lotr/sam1.png", name: "Sam", id: 8 },
      { url: "/images/lotr/sauron1.png", name: "Sauron", id: 9 },
      { url: "/images/lotr/smeagol3.png", name: "Smeagol", id: 10 },
    ],
    bgMainImg: "/images/lotr/bg2.jpg",
  },
  "Rick and Morty": {
    name: "Rick and Morty",
    logo: "/images/rickandmorty/schwifty.png",
    mainlogo: "/images/rickandmorty/header.png",
    divLogo: "/images/rickandmorty/portal1.png",
    bgHeadImage: "/images/rickandmorty/spacebg.png",
    divCol: "#383838",
    bgc: "#00afc7",
    divEffect: "star-flourish",
    currentColor: "#f8ec44",
    highColor: "#62ef24",
    cards: [
      {
        url: "/images/rickandmorty/cards/picklerick.png",
        name: "Pickle Rick",
        id: 1,
      },
      {
        url: "/images/rickandmorty/cards/rm1.png",
        name: "Mechatronics Rick",
        id: 2,
      },
      {
        url: "/images/rickandmorty/cards/rm2.png",
        name: "Dancing Rick and Morty",
        id: 3,
      },
      {
        url: "/images/rickandmorty/cards/rm3.png",
        name: "Nonchalant Rick and Morty",
        id: 4,
      },
      {
        url: "/images/rickandmorty/cards/rm4.png",
        name: "Are you seeing this Rick and Morty",
        id: 5,
      },
      { url: "/images/rickandmorty/cards/rm5.png", name: "Chef Morty", id: 6 },
      { url: "/images/rickandmorty/cards/rm6.png", name: "Anime Rick", id: 7 },
      {
        url: "/images/rickandmorty/cards/rm7.png",
        name: "Scared Morty",
        id: 8,
      },
      { url: "/images/rickandmorty/cards/rm8.png", name: "Angry Rick", id: 9 },
      {
        url: "/images/rickandmorty/cards/rm9.png",
        name: "Wub-a-lub-a-dub-dub-Rick",
        id: 10,
      },
      {
        url: "/images/rickandmorty/cards/rm10.png",
        name: "Satisfied Rick and Morty",
        id: 11,
      },
      {
        url: "/images/rickandmorty/cards/rm11.png",
        name: "Tattoo Rick",
        id: 12,
      },
      {
        url: "/images/rickandmorty/cards/rm12.png",
        name: "Confused Morty",
        id: 13,
      },
      {
        url: "/images/rickandmorty/cards/slimerick.png",
        name: "Slime Rick",
        id: 14,
      },
      { url: "/images/rickandmorty/cards/jerry.png", name: "Jerry", id: 15 },
    ],
    bgMainImg: "/images/rickandmorty/bg3.png",
  },
  Cows: {
    name: "Cows",
    logo: "/images/cows/logo2.png",
    mainlogo: "/images/cows/cowslogo.png",
    divLogo: "/images/cows/logo3.png",
    bgHeadImage: "/images/cows/headbg.png",
    divCol: "#383838",
    bgc: "black",
    divEffect: "star-flourish",
    currentColor: "#4d4b4b",
    highColor: "#e5e3e3",
    cards: [
      { url: "/images/cows/cards/bessy.png", name: "Bessy", id: 1 },
      { url: "/images/cows/cards/daisy.png", name: "Daisy", id: 2 },
      { url: "/images/cows/cards/siobhan.png", name: "Siobhan", id: 3 },
      { url: "/images/cows/cards/bertha.png", name: "Bertha", id: 4 },
      { url: "/images/cows/cards/shyvonne1.png", name: "Shyvonne", id: 5 },
      { url: "/images/cows/cards/sally.png", name: "Sally", id: 6 },
      { url: "/images/cows/cards/griswalda.png", name: "Griswalda", id: 7 },
      { url: "/images/cows/cards/helga.png", name: "Helga", id: 8 },
      { url: "/images/cows/cards/sauron.png", name: "Sauron", id: 9 },
      { url: "/images/cows/cards/mary.png", name: "Mary", id: 10 },
      { url: "/images/cows/cards/jennifer.png", name: "Jennifer", id: 11 },
      { url: "/images/cows/cards/petal.png", name: "Petal", id: 12 },
      { url: "/images/cows/cards/maisy.png", name: "Maisy", id: 13 },
      { url: "/images/cows/cards/jess.png", name: "Jess", id: 14 },
      { url: "/images/cows/cards/tess.png", name: "Tess", id: 15 },
      { url: "/images/cows/cards/ness.png", name: "Ness", id: 16 },
      { url: "/images/cows/cards/susan.png", name: "Susan", id: 17 },
      { url: "/images/cows/cards/moo.png", name: "Moo", id: 18 },
      {
        url: "/images/cows/cards/definitelycow.png",
        name: "Definitely Cow",
        id: 19,
      },
    ],
    bgMainImg: "/images/cows/bg5.jpg",
  },
}

export default data
